# Testing av implementering, logistisk regresjon

In [1]:
import numpy as np

### vekter_bias()

In [2]:
from methods import vekter_bias

In [3]:
seed = 270401
W, b = vekter_bias(10, 2)
print(W)
print(b)
print(W.shape)
print(b.shape)

[[-0.10664109]
 [-0.68190783]]
[[ 0.37234046]
 [ 0.34505273]
 [-0.23130715]
 [ 0.60755847]
 [ 0.6713692 ]
 [ 0.2974031 ]
 [ 0.26211321]
 [ 2.72578638]
 [ 0.3324763 ]
 [ 0.29913771]]
(2, 1)
(10, 1)


### output()

In [4]:
from methods import output

In [5]:
seed = 42
rng = np.random.default_rng(seed)
X = rng.random((5, 2)) # 5 observasjoner, 2 kovariater
rad, kol = np.shape(X)

W, b = vekter_bias(rad, kol, seed=seed)
print(W.shape, b.shape)

#print(np.shape(X@W + b))

y_hat = output(X, W, b)
print(y_hat.shape)

(2, 1) (5, 1)
(5, 1)


### gradient()

In [6]:
from methods import gradients

In [ ]:
n = 5
p = 2
y = rng.random((n, 1))
print(f"Shape y: {y.shape}")
X = rng.random((n, p))
print(f"Shape X: {X.shape}")
W, b = vekter_bias(n, p, seed)
print(f"Shape W: {W.shape}")
print(f"Shape b: {b.shape}")
y_hat = output(X, W, b)
print(f"Shape y_hat: {y_hat.shape}")

dCdW, dCdb = gradients(y, y_hat, X)
print(f"Shape dCdW: {dCdW.shape}")
print(f"Shape dCdb: {dCdb.shape}")



Shape y: (5, 1)
Shape X: (5, 2)
Shape W: (2, 1)
Shape b: (5, 1)
Shape y_hat: (5, 1)
Shape dCdW: (2, 1)
Shape dCdb: (5,)
[0.13412303 0.05716097 0.11763652 0.12580043 0.01817928]
